-- ============================================
-- Xevio v2 — Supabase Schema Migration
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================

-- ============================================
-- 1. ADD NEW COLUMNS TO CAMPAIGNS TABLE
-- ============================================

-- Stores the raw HTML generated by the writer (before Google Doc creation)
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS generated_html text;

-- Stores the user-edited HTML content from the TipTap editor
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS editor_content text;

-- Stores which LLM model was used for generation
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS llm_model text;

-- ============================================
-- 2. OPTIONAL: EDIT HISTORY TABLE
-- Tracks AI rewrites and manual edits in the editor
-- ============================================

CREATE TABLE IF NOT EXISTS edit_history (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  section_index integer,
  original_text text NOT NULL,
  edited_text text NOT NULL,
  edit_type text NOT NULL CHECK (edit_type IN ('manual', 'ai_rewrite')),
  ai_prompt text,
  created_at timestamptz DEFAULT now()
);

-- Index for fast lookups by campaign
CREATE INDEX IF NOT EXISTS idx_edit_history_campaign_id ON edit_history(campaign_id);

-- ============================================
-- 3. ROW LEVEL SECURITY (RLS)
-- ============================================
--
-- HOW IT WORKS:
--
-- Client-side (browser):
--   Uses NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY (publishable key)
--   Only used for: auth (login/logout) and realtime subscriptions
--   RLS policies below control what the anon key can access
--   auth.uid() resolves because the user is authenticated via supabase.auth
--
-- Server-side (API routes):
--   Uses SUPABASE_SECRET_KEY (secret key)
--   Bypasses RLS entirely — this is correct and intended
--   API routes handle their own authorization (userId checks in queries)
--   NEVER expose this key to the client (no NEXT_PUBLIC_ prefix)
--
-- n8n:
--   Also uses the service_role key in its Supabase credentials
--   Bypasses RLS — n8n needs to update any campaign regardless of user_id
--
-- REQUIRED ENV VARS (add to .env.local and Vercel):
--   SUPABASE_SECRET_KEY=<your secret/service_role key from Supabase Dashboard > Settings > API>
--
-- The anon key (NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) stays as-is for client-side auth.
-- ============================================

-- 3a. ENABLE RLS ON CAMPAIGNS
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;

-- Users can only see their own campaigns
CREATE POLICY "Users can view own campaigns"
  ON campaigns FOR SELECT
  USING (auth.uid() = user_id);

-- Users can create campaigns for themselves
CREATE POLICY "Users can insert own campaigns"
  ON campaigns FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own campaigns
CREATE POLICY "Users can update own campaigns"
  ON campaigns FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own campaigns
CREATE POLICY "Users can delete own campaigns"
  ON campaigns FOR DELETE
  USING (auth.uid() = user_id);

-- 3b. ENABLE RLS ON EDIT_HISTORY
ALTER TABLE edit_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own edit history"
  ON edit_history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own edit history"
  ON edit_history FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 4. REALTIME — ensure new columns are published
-- ============================================
-- The existing realtime subscription in your app listens for
-- changes on the campaigns table. New columns (generated_html,
-- editor_content, llm_model) are automatically included in
-- realtime payloads — no action needed here.
--
-- Realtime uses the anon key with the authenticated user's JWT,
-- so RLS policies apply. The user will only receive updates for
-- campaigns where auth.uid() = user_id — which is already the case
-- since the subscription filters by campaign ID.
--
-- If you ever need to explicitly enable realtime:
-- ALTER PUBLICATION supabase_realtime ADD TABLE campaigns;

-- ============================================
-- 5. VERIFICATION QUERIES
-- Run these after the migration to confirm everything worked
-- ============================================

-- Check new columns exist
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'campaigns'
  AND column_name IN ('generated_html', 'editor_content', 'llm_model');

-- Check edit_history table exists
SELECT table_name FROM information_schema.tables
WHERE table_name = 'edit_history';

-- Check RLS is enabled
SELECT tablename, rowsecurity
FROM pg_tables
WHERE tablename IN ('campaigns', 'edit_history');

-- Check policies exist
SELECT tablename, policyname
FROM pg_policies
WHERE tablename IN ('campaigns', 'edit_history');
